-- Committed deliberately, and it does nothing.
--
-- `buddy migrate` reported this as "rebuild table projects (type/constraint
-- change) [destructive]" on every run and refused to apply it
-- non-interactively, which failed the deploy at the migrate step. The table it
-- builds is byte-for-byte identical to the one already in production: same
-- columns, same types, same defaults, same unique index (twice - the generator
-- emits both `projects_ingest_key_unique` and the double-prefixed
-- `projects_projects_ingest_key_unique`). Verified by diffing the CREATE TABLE
-- below against sqlite_master on the box.
--
-- The diff is spurious, but it does not clear on its own. Running it once
-- records it as applied and `--diff` then reports a clean schema. Proven
-- against a copy of the production database first: 1 project, 2 users and
-- 2 log entries all survived, and the second diff was empty.
--
-- See stacksjs/stacks#2346 for the related migration-generator problems.
-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_projects" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT not null,
  "platform" TEXT,
  "dsn" TEXT,
  "ingest_key" TEXT,
  "owner_id" INTEGER,
  "is_active" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
INSERT INTO "_qb_tmp_projects" ("id", "name", "platform", "dsn", "ingest_key", "owner_id", "is_active", "created_at", "updated_at") SELECT "id", "name", "platform", "dsn", "ingest_key", "owner_id", "is_active", "created_at", "updated_at" FROM "projects";
DROP TABLE "projects";
ALTER TABLE "_qb_tmp_projects" RENAME TO "projects";
CREATE UNIQUE INDEX IF NOT EXISTS "projects_ingest_key_unique" ON "projects" ("ingest_key");
CREATE UNIQUE INDEX IF NOT EXISTS "projects_projects_ingest_key_unique" ON "projects" ("ingest_key");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
