#!/usr/bin/env bun
/**
 * Typecheck the TypeScript inside .stx files.
 *
 * `tsc --noEmit` cannot see into a .stx file, so every annotation in every
 * script block is unverified: `const x: number = 'a string'` renders, ships, and
 * passes both the linter and the typechecker. Annotations that nothing checks
 * decay — the framework's own composables/use-storage.d.ts declares
 * useLocalStorage returning `void` while the implementation returns a signal.
 *
 * This extracts each script block into a real .ts file under a scratch tree and
 * runs tsc over it, so a wrong annotation fails.
 *
 * WHAT IT MODELS, AND WHERE IT APPROXIMATES
 *
 * A server block and the client block below it are emitted into ONE module, in
 * that order. That mirrors the runtime: the server-to-client bridge injects the
 * server block's top-level values as `var` declarations at the top of the client
 * script, so the client genuinely does see them. It is an approximation in one
 * direction — the bridge drops functions and `__`-prefixed names, so this is
 * slightly more permissive about what a client script may reference.
 *
 * Server blocks are emitted as modules so their top-level `await` is legal.
 *
 * Names the serve layer injects into a server block's scope (`cookies`,
 * `params`, `__stxServeSearch`, `requestContext`) are declared in the generated
 * ambient file, because they exist at runtime and are in no .d.ts.
 */
import { Glob } from 'bun'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const OUT = '.stx-typecheck'
const SCRIPT = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi

/**
 * Replace stx template interpolation with a valid TypeScript expression.
 *
 * A client script body may contain `{{ expr }}` / `{!! expr !!}`, which the
 * renderer substitutes before the browser sees it — `{{ }}` becomes a
 * JSON.stringify'd literal and `{!! !!}` becomes the raw value. Neither is
 * TypeScript, so tsc reports a parse error and never reaches the annotations we
 * actually want checked.
 *
 * Substituted with `(null as any)` rather than a string literal because the
 * interpolation can appear anywhere an expression can, and `any` is assignable
 * to whatever the surrounding code expects. Same-line replacement, so reported
 * line numbers still map back to the .stx.
 */
function stripInterpolation(body: string): string {
  return body
    .replace(/\{!!([\s\S]*?)!!\}/g, '(null as any)')
    .replace(/\{\{([\s\S]*?)\}\}/g, '(null as any)')
}

/** Blocks stx does not compile as TypeScript, or does not compile at all. */
function isTypeScriptBlock(attrs: string): boolean {
  if (/\blang\s*=\s*["']js["']/.test(attrs)) return false // explicitly opted out
  if (/\bsrc\s*=/.test(attrs)) return false // external file
  if (/\btype\s*=\s*["']application\/json["']/.test(attrs)) return false
  return true
}

rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

// Ambient declarations for the values the serve layer injects into a server
// block. These are real at runtime (bun-plugin-stx serve.js writes them onto the
// render context) and declared in no shipped .d.ts.
writeFileSync(join(OUT, 'stx-injected.d.ts'), `// GENERATED by scripts/check-stx-types.ts — do not edit.
declare const cookies: Record<string, string>
declare const params: Record<string, string>
declare const __stxServeSearch: string
declare const __stxServeContext: unknown
declare const requestContext: {
  cookie?: (name: string) => string | undefined
  url?: () => string
} | undefined
declare const $props: Record<string, any>
declare const props: Record<string, any>
`)

let files = 0
let blocks = 0
const emitted: string[] = []

for (const file of (await Array.fromAsync(new Glob('resources/**/*.stx').scan('.'))).sort()) {
  const src = await Bun.file(file).text()
  const parts: string[] = []

  for (const m of src.matchAll(SCRIPT)) {
    if (!isTypeScriptBlock(m[1])) continue
    const body = stripInterpolation(m[2]).trim()
    if (!body) continue
    const kind = /\bserver\b/.test(m[1]) ? 'server' : 'client'
    // Line offset so a tsc error points near the right place in the .stx.
    const line = src.slice(0, m.index).split('\n').length
    parts.push(`// ---- ${kind} block, ${file}:${line} ----\n${body}`)
    blocks++
  }

  if (!parts.length) continue
  const out = join(OUT, `${file.replace(/[^\w]/g, '_')}.ts`)
  mkdirSync(dirname(out), { recursive: true })
  // `export {}` forces module scope, which makes top-level await legal and stops
  // declarations in one file colliding with another's.
  writeFileSync(out, `${parts.join('\n\n')}\n\nexport {}\n`)
  emitted.push(out)
  files++
}

writeFileSync(join(OUT, 'tsconfig.json'), JSON.stringify({
  extends: '../tsconfig.json',
  compilerOptions: {
    noEmit: true,
    // The blocks reference each other's bindings and the runtime's globals; we
    // are checking the annotations the author wrote, not the framework's.
    skipLibCheck: true,
    types: ['bun'],
  },
  include: ['./**/*.ts', './**/*.d.ts', '../types/**/*.d.ts'],
}, null, 2))

console.error(`extracted ${blocks} script blocks from ${files} .stx files into ${OUT}/`)

const proc = Bun.spawnSync(['bun', 'x', 'tsc', '-p', join(OUT, 'tsconfig.json')], {
  stdout: 'pipe',
  stderr: 'pipe',
})
const output = (proc.stdout.toString() + proc.stderr.toString()).trim()
if (output) console.error(`${output}\n`)

/**
 * Two error classes are artefacts of how blocks are extracted, not defects in
 * the .stx source. They are counted separately so the real findings are not
 * buried, and so nobody "fixes" source to satisfy the harness.
 *
 *   TS2451 — a client block redeclaring a name the server block also declares.
 *            Legal at runtime and in fact meaningful: the bridge deliberately
 *            skips injecting any name the client redeclares. Concatenating the
 *            two blocks into one module is what makes it look like an error.
 *   TS2307 — a relative import (`../../config/services`) resolved from the
 *            scratch tree instead of the file's real directory. Fixing this
 *            means mirroring the original depth on emit.
 */
const ARTEFACTS = new Set(['TS2451', 'TS2307'])
const lines = output.split('\n').filter(l => /error TS\d+/.test(l))
const counts = new Map<string, number>()
for (const l of lines) {
  const code = /error (TS\d+)/.exec(l)?.[1] ?? 'TS?'
  counts.set(code, (counts.get(code) ?? 0) + 1)
}
const artefact = lines.filter(l => ARTEFACTS.has(/error (TS\d+)/.exec(l)?.[1] ?? '')).length
const real = lines.length - artefact

console.error(`${lines.length} findings — ${real} in source, ${artefact} extraction artefacts (${[...ARTEFACTS].join(', ')})`)
console.error([...counts].sort((a, b) => b[1] - a[1]).map(([c, n]) => `  ${c} x${n}`).join('\n'))

// Advisory by default. The extraction is not yet faithful enough to gate a
// build on — see the artefact classes above — and a harness that cries wolf
// gets switched off. Run with --strict once those are handled.
const strict = process.argv.includes('--strict')
if (!strict) {
  console.error('\nadvisory run — pass --strict to fail on findings')
  process.exit(0)
}
process.exit(real > 0 ? 1 : 0)
